spring:
  datasource:
    url: replace-with-database-url # For example: jdbc:postgresql://localhost:5432/delivery
    username: replace-with-username
    password: replace-with-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

api:
  token: b79b16c2-2f77-450f-91a5-868c3c698a82
  secret:
    key: dOJWwjp+BWqUcof3K+3OW6XGTnEpmWerx64TCNk0+0pZnonHdN99NFRIGaJSX0/HTtiu6AGYpKp0mjguzqp+wg==

server:
  port: 8070