spring:
  datasource:
    url: replace-with-database-url # For example: jdbc:postgresql://localhost:5432/order
    username: replace-with-username
    password: replace-with-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.ecommerce.kafka.OrderConfirmation

application:
  config:
    product-url: http://localhost:8030/api/v1/variants
    payment-url: http://localhost:8060/api/v1/payments
    payment-method-url: http://localhost:8060/api/v1/payment-methods
    delivery-method-url: http://localhost:8070/api/v1/delivery-methods
    cart-url: http://localhost:8040/api/v1/carts

server:
  port: 8050

