application:
  security:
    jwt:
      secret-key: 65d61a45e83ba8e00ee8f3a4a95db6240ac8b3ae2fcb782ef8e3654025dcc27f # recommended to generate own key
      expiration: 3600000 # in ms
      refresh-token:
        expiration: 604800000 # in ms

spring:
  datasource:
    url: replace-with-database-url # For example: jdbc:postgresql://localhost:5432/user
    username: replace-with-username
    password: replace-with-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8010
