CREATE TABLE IF NOT EXISTS cart (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS cart_seq INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS cart_item (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL,
    cart_id BIGINT NOT NULL,
    quantity INT NOT NULL,

    FOREIGN KEY (cart_id)
    REFERENCES cart(id)
    ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS cart_item_seq INCREMENT BY 1;